### ISSUE TITLE
'mix licenses' doesn't work in Elixir 1.9

### ISSUE THREAD

**Issue by garthk** [opencensus-beam/opencensus_honeycomb#6]
Warning shot during `mix deps.compile` with 1.8.2:
```
warning: Mix.Dep.loaded/1 is deprecated. Mix.Dep.loaded/1 was private API and you should not use it
  lib/licensir/scanner.ex:35
```
Failure with 1.9.4:
```
$ mix licenses
Notice: This is not a legal advice. Use the information below at your own risk.
** (UndefinedFunctionError) function Mix.Dep.loaded/1 is undefined or private
    (mix) Mix.Dep.loaded([])
    lib/licensir/scanner.ex:27: Licensir.Scanner.scan/0
    lib/mix/tasks/licenses.ex:18: Mix.Tasks.Licenses.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

**Comment by garthk** [comment]
For now, to get the “right” Elixir and Erlang with `asdf`:

* `asdf plugin-add elixir`
* `asdf plugin-add erlang`
* `asdf install elixir 1.8.2-otp-21`
* `asdf install erlang 21.3.8.6`
* `asdf local elixir 1.8.2-otp-21`
* `asdf local erlang 21.3.8.6`
